# Site-wide settings
title: the beginning of the end
author:
  name: test
  email: compoundingbox@hotmail.com
description: 
  The physician who knows only medicine, knows not even medicine
  
# Build settings
# Use 'theme' for local development or 'remote_theme' for GitHub Pages
theme: minima

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Suppress Sass deprecation warnings
sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings (Minima v3+)
minima:
  # Available skins: classic, dark, auto, solarized-light, solarized-dark, solarized.
  skin: classic

  # Specific pages for site navigation.
  nav_pages:
    - about.md

  # Show excerpts on the homepage.
  show_excerpts: true

  # Minima date format (e.g. Jan-01-2024).
  # date_format: "%b-%d-%Y"

  # Social Media Links (Renders icons in footer)
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/afrw"
    - title: X
      icon: x-twitter
      url: "https://X.com"

  # Set to true to hide the RSS link in the footer
  hide_site_feed_link: true

timezone: America/Grenada
future: true
umami_id: b671a501-e000-4892-911b-04729163d32f
site.title: the beginning of the end
